language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules

services: 
  - docker

script:
  - npm run test
  - npm run docker:prod
  # - npm run docker:down 

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
notifications:
  email:
    - adedapopaul@yahoo.com