version: "3"
services:
  app:
    container_name: card-server-restful-api
    restart: always
    build: .
    volumes:
      - .:/app
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:4000"
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  